server:
  port: 8081
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://47.110.145.251:3306/interview?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: interview
    password: 7fbfy2Xrt5z78bPh
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource